trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Updated Node.js version to 14.x
  displayName: 'Install Node.js'

- script: |
    cd .Script_DevOps_Dynamic_Document  # Navigate to the script directory
    npm install  # Install project dependencies using npm
    # Assuming test.js is your entry script file, replace it with your actual script filename
    node test.js  
  displayName: 'Run Node.js script'

- script: |
    npm install  # Install project dependencies
  displayName: 'Install Dependencies'

- script: |
    cd .Script_DevOps_Dynamic_Document  # Navigate to the script directory
    npm install  # Install project dependencies
  displayName: 'Install Dependencies and Fix Missing Modules'

- script: |
    npm install  # Install project dependencies
    npm audit  # Run npm audit to review any compatibility warnings or errors
  displayName: 'Install Dependencies and Review Compatibility Warnings'

- script: |
    # Your additional testing steps here
  displayName: 'Test and Iterate'
